# Generated by Django 5.1.4 on 2025-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moto', '0003_alter_applycompany_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applycompany',
            name='upload_resume',
            field=models.FileField(upload_to='upload_resume_doc/'),
        ),
    ]
