# Generated by Django 5.1.4 on 2025-01-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moto', '0004_alter_applycompany_upload_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applycompany',
            name='user',
        ),
        migrations.AddField(
            model_name='applycompany',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
